# Generated by Django 4.1.2 on 2022-11-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderproduct_discount_productinbasket_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
    ]
