# Generated by Django 4.1.2 on 2022-12-23 07:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=48),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductInBasket',
        ),
    ]
