# Generated by Django 4.1.2 on 2022-10-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_unit_product_article_productimage_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='leftover',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
