# Generated by Django 4.1.2 on 2022-12-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productunit_product_code_product_id_1c_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunit',
            name='code',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=25, null=True),
        ),
    ]
